-- Create table for Amalan Records
create table if not exists amalan_records (
  id bigint generated by default as identity primary key,
  student_name text not null,
  day integer not null,
  sholat_subuh text,
  sholat_dzuhur text,
  sholat_ashar text,
  sholat_maghrib text,
  sholat_isya text,
  sholat_tarawih text,
  sahur boolean default false,
  puasa boolean default false,
  sholat_dhuha boolean default false,
  infaq boolean default false,
  dzikir boolean default false,
  itikaf boolean default false,
  help_activity text,
  help_description text,
  quran_type text,
  quran_note text,
  quran_pages integer default 0,
  total_exp integer default 0,
  updated_at timestamp with time zone default timezone('utc'::text, now()),
  unique(student_name, day)
);

-- Create table for Inquiries
create table if not exists inquiries (
  id bigint generated by default as identity primary key,
  student_name text not null,
  subject text not null,
  message text not null,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable Row Level Security (RLS)
alter table amalan_records enable row level security;
alter table inquiries enable row level security;

-- Create policies (allow public access for this demo app, or restrict as needed)
-- For simplicity in this demo, we allow all operations. In production, restrict based on auth.
create policy "Enable all access for all users" on amalan_records for all using (true) with check (true);
create policy "Enable all access for all users" on inquiries for all using (true) with check (true);
